### ISSUE TITLE
proposal status is missing important data

### ISSUE THREAD

**Issue by jbibla** [luniehq/lunie-light#281] opened 2020-11-25 16:57 UTC
<img width="997" alt="Screen Shot 2020-11-25 at 11 57 02 AM" src="https://user-images.githubusercontent.com/6021933/100258720-62014080-2f15-11eb-800d-37c3f01d3c6d.png">

**Comment by faboweb** [comment] 2020-11-25 17:11
what data are you expecting? is this on a fork or on master?

**Comment by jbibla** [comment] 2020-11-25 17:53
on master and cosmos fork - a bunch of data is missing

<img width="1062" alt="Screen Shot 2020-11-25 at 12 52 56 PM" src="https://user-images.githubusercontent.com/6021933/100264677-266a7480-2f1d-11eb-81de-87b18b3e9c6f.png">

**Comment by faboweb** [comment] 2020-11-25 18:07
On akash the data is there: https://lunie-akash.vitwit.com/proposals/1

**Comment by faboweb** [comment] 2020-11-25 18:14
where do you get no data? the bar does only show for deposits

**Comment by Bitcoinera** [comment] 2020-11-26 11:18
Which network is this? It is in voting period? What proposal is it?

**Comment by jbibla** [comment] 2020-11-26 15:37
all proposals on stargate-4 and cosmoshub-3

**Comment by Bitcoinera** [comment] 2020-11-26 15:46
> all proposals on stargate-4 and cosmoshub-3

It looks good for cosmoshub-3

![image](https://user-images.githubusercontent.com/40721795/100370640-dbc52700-3006-11eb-8af4-12e2f65450a5.png)

**Comment by Bitcoinera** [comment] 2020-11-26 15:50
Stargate test proposal seems to not have received any deposits: http://localhost:8010/proxy/gov/proposals/2/deposits

It could also be that it needs a different query :shrug: 

It is also strange that being the first it's got the id "2"

**Comment by jbibla** [comment] 2020-11-26 16:00
so data is just missing on stargate i guess

**Comment by Bitcoinera** [comment] 2020-11-26 16:03
> so data is just missing on stargate i guess

It gets the description though. In any case it would be an endpoint question

**Comment by jbibla** [comment] 2020-11-26 17:07
not sure what you mean by that - http://localhost:8010/proxy/gov/proposals/2 should have everything needed to display the text and ID

**Comment by Bitcoinera** [comment] 2020-11-27 11:28
> not sure what you mean by that

I mean that the normal proposal deposit endpoint returns `null`. The REST API endpoint, I mean, `gov/proposals/{proposalId}/depostis`. Wonder if there is a new way to query for this in Stargate. This is under heavy development and unforeseeable what is to come.

For now it looks broken:

http://localhost:8010/proxy/gov/proposals/2 returns:

![image](https://user-images.githubusercontent.com/40721795/100444558-e4236d80-30ab-11eb-827c-41e37d5811ca.png)

But http://localhost:8010/proxy/gov/proposals/2/deposits returns:

![image](https://user-images.githubusercontent.com/40721795/100444590-f3a2b680-30ab-11eb-9ecd-0480b92d8cab.png)

I could fix it to show the total deposit, but cannot do like we had, list of depositors with their deposit... I don't think it is worth it to do this fix though, since this is promptly going to change, and v0.39 works well

**Comment by Bitcoinera** [comment] 2020-11-27 11:44
> not sure what you mean by that - http://localhost:8010/proxy/gov/proposals/2 should have everything needed to display the missing text, date, and ID

Mmm, actually I think it is all good, now thinking about it :thinking: 

I think because the deposit period passed, then you get `null`. Yes, I just confirmed: https://lcd.nylira.net/gov/proposals/26/deposits

OK, so then it is all good actually. There wasn't any vote so that is why it is like it is. But there is no field missing actually. All good

**Comment by Bitcoinera** [comment] 2020-11-27 11:45
We should close this as there is actually no bug

**Comment by jbibla** [comment] 2020-11-27 12:27
every proposal, no matter the state, should have a sentence that references time and it should display the ID. this data is available for every proposal all the time: https://lcd.nylira.net/gov/proposals/26

`"voting_end_time": "2020-06-04T18:00:11.292428073Z"`
`"id": "26"`

**Closed** 2020-11-27 16:58 UTC
Labels: bug
